### ISSUE TITLE
Parameter workStatus of suso_export() do not behave as described on documentation

### ISSUE THREAD

**Issue by Pablo-Leon-INE** [michael-cw/SurveySolutionsAPI#1]
On documentation is stated:
> workStatus :   define which statuses the file should inlude (i.e. ...), **if NULL all is exported** .

But the code inside the function does this:
```
workStatus<-match.arg(workStatus, margs)
```
Where `margs` is  :
["Restored","Created","SupervisorAssigned","InterviewerAssigned","RejectedBySupervisor","ReadyForInterview","SentToCapi","Restarted","Completed","ApprovedBySupervisor","RejectedByHeadquarters","ApprovedByHeadquarters","Deleted"] 

The `match.arg()` documentation says on _Arguments_ section:
> arg   : a character vector (of length one unless several.ok is TRUE) or NULL.

And on _Details_ section:
> In the one-argument form match.arg(arg), the choices are obtained from a default setting for the formal argument arg of the function from which match.arg was called.
> (Since default argument matching will set arg to choices, this is allowed as an exception to the ‘length one unless several.ok is TRUE’ rule, and returns the first element.)

The wording is not very clear, but means that if length of arg is not 1 (as it happens to be when arg is NULL). the first element of `choice` is returned.

And the code of `match.arg()` contains:
```
    if (is.null(arg)) 
        return(choices[1L])
```

So `workStatus` ends up with the value "Restored", which is not the documented behaviour for `suso_export()`.

Regards
- Pablo

**Comment by michael-cw** [comment]
Thanks so much Pablo, you had been perfectly right. With the new release, we will switch to v2 of the Survey Solutions API, and will include the following change:

if(!is.null(workStatus)) {
    workStatus<-match.arg(workStatus, margs)
  } else {
    workStatus<-"All"
  }

This should lead to the behavior as described in the documentation. And apologize also for my slow reaction, but the switch to v2 was planned since long, and that change was held back to do it in one release. Hope the package is useful. If any functionalities are missing, let me know. Always happy to incorporate user feedback.
