### ISSUE TITLE
Interview ID not consistent

### ISSUE THREAD

**Issue by ashwinikalantri** [michael-cw/SurveySolutionsAPI#2]
The Interview ID that we get using `suso_getAllInterviewQuestionnaire` command and `suso_export` command are different.

`suso_getAllInterviewQuestionnaire` - `bb6c5d61-889c-4b9d-90f9-7f89f22deb45`
`suso_export` - `bb6c5d61889c4b9d90f97f89f22deb45`

`suso_getAllInterviewQuestionnaire` has '-' while `suso_export` doesn't.

**Comment by michael-cw** [comment]
This is correct, thank you very much. It is actually a result of the API return value which we have not further sanitized. 

Internally, that is in an API call, this does not matter, however outside of it this is problematic. With switch to v2 of the API, this will be harmonized.

**Comment by ashwinikalantri** [comment]
When can we expect an update for the V2 API?

**Comment by michael-cw** [comment]
Just in the final testing stage and hope to have the update released by end of week. It became a bit a bigger release eventually, since i also added graphql support https://demo.mysurvey.solutions/graphql?sdl

Not fully implemented, but it is a new API implemented by Survey Solutions end of last year. It allows a much higher degree of query flexibility.
https://www.apollographql.com/blog/three-ways-to-represent-your-graphql-schema-a41f4175100d/

**Comment by ashwinikalantri** [comment]
Great! Looking forward!

**Comment by ashwinikalantri** [comment]
Do we have any update of the release?
